# publication settings

lang: en

toc-title: "Contents"
reference-section-title: "Bibliography"
link-citations: true

  download settings

download: # full-text outputs
  - label: PDF
    link: the-relation-between-content-classification-and-ux-aspects-in-documentation-portals.pdf
  #  - label: EPUB
  #    link: text.epub
  #  - label: DOCX
  #    link: text.docx
  #  - label: LaTeX
  #    link: text.tex
  #  - label: Markdown
  #    link: text.md
  #  - label: OAI-PMH
  #    link: text.xml
  - label: Source
    link: https://github.com/utaschulz1/TCLocThesis
