name: Publish Open Textbook

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
    paths-ignore:
      - "original/**"
      - "README.md"

jobs:
  publish_textbook:
    runs-on: ubuntu-latest # Updated to use ubuntu-latest for flexibility
    steps:
      # Step 1: Checkout the repository
      - name: Download Source Files
        uses: actions/checkout@v3

      # Step 2: Enable Homebrew
      - name: Enable Homebrew
        uses: raviqqe/enable-homebrew@v0.1.0

      # Step 3: Install Pandoc
      - name: Setup Pandoc
        run: brew install pandoc pandoc-crossref

        Step 4: Setup TinyTeX
      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v2

      - name: TeX Dependencies
        run: |
          tlmgr --version
          tlmgr install $(cat lib/latex-packages.txt)

        

      # Step 4: Install LaTeX (Replace PagedJS)
      #- name: Install TexLive
        #run: sudo apt-get install -y texlive-full

      # Step 5: Build the website and PDF
      - name: Build Website and PDF
        run: |
          bash lantern.sh
          touch ./public/.nojekyll
          
      #Debug
      - name: Debug LaTeX Logs
        run: |
          echo "Checking LaTeX logs..."
          find . -name "*.log" -exec cat {} \;

      # Step 6: Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/
          
     
